name: JumpscarePlugin
version: 1.0.0
main: ntdotjsx.jumpscare.JumpscarePlugin
api-version: '1.21'

commands:
  jumpscare:
    description: Trigger jumpscare on a player
    usage: /jumpscare_model <player>
    permission: jumpscare.use